export const SET_ACCOUNT = 'SET_ACCOUNT';

//POOL ACTIONS
export const POOL_SET_POOL_INFO = 'POOL_SET_POOL_INFO';
export const POOL_SET_STAKE_TOKEN_INFO = 'POOL_SET_STAKE_TOKEN_INFO';
export const POOL_SET_REWARD_TOKEN_INFO = 'POOL_SET_REWARD_TOKEN_INFO';
export const POOL_SET_CONTRACT = 'POOL_SET_CONTRACT';
export const POOL_SET_STAKE_TOKEN_CONTRACT = 'POOL_SET_STAKE_TOKEN_CONTRACT';
export const POOL_SET_REWARD_TOKEN_CONTRACT = 'POOL_SET_REWARD_TOKEN_CONTRACT';
export const POOL_APPROVE_TOKEN = 'POOL_APPROVE_TOKEN';
export const POOL_LOAD_ALLOWANCE = 'POOL_LOAD_ALLOWANCE';
export const POOL_APPROVE_TOKEN_SUCCESS = 'POOL_APPROVE_TOKEN_SUCCESS';
export const POOL_STAKE = 'POOL_STAKE';
export const POOL_WITHDRAW_ALL = 'POOL_WITHDRAW_ALL';
export const POOL_HARVEST = 'POOL_HARVEST';
export const POOL_EXIT = 'POOL_EXIT';
export const POOL_GET_EARNED = 'POOL_GET_EARNED';
export const POOL_GET_EARNED_SUCCESS = 'POOL_GET_EARNED_SUCCESS';
export const POOL_GET_STAKED = 'POOL_GET_STAKED';
export const POOL_GET_STAKED_SUCCESS = 'POOL_GET_STAKED_SUCCESS';
export const POOL_GET_STAKE_TOKEN_BALANCE = 'POOL_GET_STAKE_TOKEN_BALANCE';
export const POOL_GET_STAKE_TOKEN_BALANCE_SUCCESS = 'POOL_GET_STAKE_TOKEN_BALANCE_SUCCESS';
export const POOL_GET_TOTAL_STAKED_SUCCESS = 'POOL_GET_TOTAL_STAKED_SUCCESS';
export const POOL_GET_PERIOD_FINISH = 'POOL_GET_PERIOD_FINISH';
export const POOL_GET_PERIOD_FINISH_SUCCESS = 'POOL_GET_PERIOD_FINISH_SUCCESS';